volumes:
  db_volume:
services:
  app:
    container_name: express-ts-app
    build:
      context: .
    ports:
    - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=${DB_URL}
      - TEST_DB_URL=${TEST_DB_URL}
    restart: always
  database:
    container_name: mongo_db_community
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    healthcheck:
      test: mongosh mongodb://database:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - MONGODB_INITDB_BIND_IP=0.0.0.0
    volumes:
      - db_volume:/data/db
