volumes:
  db_volume:
services:
  app:
    container_name: express-ts-app
    build:
      context: .
    ports:
    - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - TEST_DB_URL=${TEST_DB_URL}
    restart: always
  database:
    container_name: mongo_db_community
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    healthcheck:
      test: mongosh mongodb://database:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db_volume:/data/db
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    depends_on:
      - zookeeper
    container_name: broker
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    ports:
      - 2181:2181

